# default settings, should be overwritten

TCEpage:
  author: 'kuhprovincialdata'
  author_email: info@kuhprovincialdata.ch
  author_phone: '+41790000000'
  org_name: 'kuhprovincialdata'
  org_logo: 'EXT:kuhprovincialdata/Resources/Public/Images/logo.png'

# Das ist ein Test
